### ISSUE TITLE
The install.py is not working

### ISSUE THREAD

**Issue by de-adshot** [M4cs/BabySploit#11]
The install.py is not working

root@kali:~/BabySploit# python install.py 
 ==  BabySploit Installation  ==
Press ENTER To Start Installation
Traceback (most recent call last):
  File "install.py", line 33, in <module>
    start()
  File "install.py", line 21, in start
    input("Press ENTER To Start Installation")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

--------------------------------------------------------------------------------------------------------------------------------

later i tried pip cmd, as follows

root@kali:~/BabySploit# pip install requirements.txt 
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

I'm not sure what am I missing.

**Comment by M4cs** [comment]
Firstly you must use Python3 to run the install. So `sudo python3 install.py`. Then to install pip modules you need to add the -r arg before requirements.txt. So pip3 install -r requirements.txt.

**Comment by actwoply** [comment]
same problem as Avinash125 and also

Press ENTER To Start Installation
 [10:19:44] Installing Required Dependencies...         [STATUS] Processing^CTraceback (most recent call last):
  File "install.py", line 33, in <module>
    start()
  File "install.py", line 28, in start
    print(Command_exe("["+time.strftime('%H:%M:%S')+"] Installing Required Dependencies...        ",'apt-get install exploitdb netcat nmap php7.0 perl'))
  File "install.py", line 9, in Command_exe
    if subprocess.call(cmd +' >/dev/null 2>&1', shell=True)==0:
  File "/usr/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

**Comment by M4cs** [comment]
I have just pushed an update to Install.py that should fix the issue of it getting stuck on there.

**Comment by actwoply** [comment]
it still hangs but now i get

[STATUS] ProcessingTraceback (most recent call last):
                               File "install.py", line 40, in <module>
                                                                          start()
   File "install.py", line 35, in start
                                           print(Command_exe("["+time.strftime('%H:%M:%S')+"] Installing Required Dependencies...        ",'apt-get install exploitdb netcat nmap php7.0 perl -y'))
                                     File "install.py", line 9, in Command_exe
                                                                                  if subprocess.call(cmd +' >/dev/null 2>&1', shell=True)==0:
                                                               File "/usr/lib/python3.6/subprocess.py", line 269, in call
                                             return p.wait(timeout=timeout)
                                                                             File "/usr/lib/python3.6/subprocess.py", line 1457, in wait
                                                            (pid, sts) = self._try_wait(0)
            File "/usr/lib/python3.6/subprocess.py", line 1404, in _try_wait
                                                                                (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by M4cs** [comment]
Remove the kali source from /etc/apt/sources.list and then run install. It will take a long time because exploitdb is HUGE. So just wait for it.

**Comment by actwoply** [comment]
sorry no... my sources list was already removed# 

# deb cdrom:[Debian GNU/Linux 2018.2 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180412-12:50]/ kali-last-snapshot contrib main non-free

#deb cdrom:[Debian GNU/Linux 2018.2 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180412-12:50]/ kali-last-snapshot contrib main non-free

deb http://http.kali.org/kali kali-rolling main non-free contrib
# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

**Comment by M4cs** [comment]
Okay well jsut run install.py and wait for it to finish

**Comment by actwoply** [comment]
now i get ...
root@i5:~/BabySploit# install.py
bash: install.py: command not found
root@i5:~/BabySploit# python install.py
 ==  BabySploit Installation  ==
Press ENTER To Start Installation
Traceback (most recent call last):
  File "install.py", line 40, in <module>
    start()
  File "install.py", line 21, in start
    input("Press ENTER To Start Installation")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by M4cs** [comment]
`python3` please. Its a python3 program.

**Comment by ghost** [comment]
But python2 is very best

**Comment by actwoply** [comment]
so far so good... now this..


now i get ...
root@i5:~/BabySploit# install.py
bash: install.py: command not found
root@i5:~/BabySploit# python install.py
 ==  BabySploit Installation  ==
Press ENTER To Start Installation
Traceback (most recent call last):
  File "install.py", line 40, in <module>
    start()
  File "install.py", line 21, in start
    input("Press ENTER To Start Installation")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by M4cs** [comment]
Can you please read the readme? It says clearly in the Readme to run `sudo python3 install.py`. Not `python install.py`

**Comment by actwoply** [comment]
i did the python3...sorry thought i said that

**Comment by actwoply** [comment]
pretty cool so far... raccoon doesnt work for me ...still trying everything ;)

**Comment by M4cs** [comment]
run raccoon --help

**Comment by actwoply** [comment]
and also i get this for update...

[!] Update Found | Version: 1.0-0.1.10 [!]
[y\n] y
Traceback (most recent call last):
  File "start.py", line 15, in <module>
    updater.checkupdate()
  File "/root/BabySploit/babysploit/updater.py", line 27, in checkupdate
    print(Command_exe("["+time.strftime('%H:%M:%S')+"] Fetching Update...             ",'git fetch --all'))
NameError: name 'time' is not defined

**Comment by actwoply** [comment]
and raccoon --help gives me this...
[babysploit]> raccoon --help
sh: 1: raccoon: not found

**Comment by actwoply** [comment]
and having problems starting babysploit again

root@i5:~/BabySploit# python3 start.py
Traceback (most recent call last):
  File "start.py", line 5, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'

**Comment by M4cs** [comment]
Did you run pip3 install -r requirements.txt?

**Comment by M4cs** [comment]
Also run `git fetch --all` and `git reset --hard origin/master`
